In [2]:
import numpy as np
np1=np.array([1,2,3,4,5])
# type(np1) #numpy.ndarray
# np1 #array([1, 2, 3, 4, 5])
# print(np1[4])
np2=np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44]])

print(np2[1,[3]])
print(np2[1][2])



[8]
7


In [42]:
# np.zeros(4) array([0., 0., 0., 0.])
# np.ones(4) array([1., 1., 1., 1.])

# np.empty(2)

np.arange(10)

np.arange(2,13,2) #array([ 2,  4,  6,  8, 10, 12])

arr=np.array([2,1,5,6,7,8,956,4])
a=np.sort(arr)

type(a)


arr



array([  2,   1,   5,   6,   7,   8, 956,   4])

In [69]:
# arr1=np.array([2,1,5,6,7,8,956,4])
# arr2=np.array([1,3,5,6,7,8,9,0])
# np.concatenate((arr1,arr2),axis=0)

# arr3=np.array[[[1,2,3],[1,2,3]],
#               [[1,2,3],[1,2,4]]]

# arr=np.array([[[0, 0, 0], [0, 0, 0], [0, 0, 0]])
             
three_dim_array = np.array(
    [[[1, 2, 3], 
      [4, 5, 6]],
    [[7, 8, 9], 
      [10, 11, 12]]
     ])
# print(three_dim_array)

b = three_dim_array.reshape(12,) # [ 1  2  3  4  5  6  7  8  9 10 11 12]
print(b)




[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [72]:
arr8=np.array([1,2,3,4,5,6])
arr8.save('ap')
np.load('ap')

AttributeError: 'numpy.ndarray' object has no attribute 'save'

In [83]:
a=np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([1, 2])
np.savez('avash.ipynp')
data = np.load('avash.ipynp.npz')
print(data)





TypeError: save() missing 1 required positional argument: 'arr'

In [85]:
ar1=np.array([1,2,3,4,5])

In [86]:
arr1


array([  2,   1,   5,   6,   7,   8, 956,   4])

In [21]:
import pandas as pd
import numpy as np
arr10=np.array([['awash','ayusha','paudel','sagarmath'],["ap","cp","bp","dp"],["ep","fp",'annapurna','macchhapuchre']])

In [22]:
df=pd.DataFrame(arr10)

In [23]:
df.to_csv('./files/ap.csv')

In [24]:
pd.read_csv('./files/ap.csv')

Unnamed: 0      0       1          2              3
0           0  awash  ayusha     paudel      sagarmath
1           1     ap      cp         bp             dp
2           2     ep      fp  annapurna  macchhapuchre

In [26]:
arr10=np.array([10,20,30,40,50])

In [29]:
np.savetxt('./files/simpleFile.csv',arr10)


In [33]:
np.loadtxt('./files/simpleFile.csv')

array([10., 20., 30., 40., 50.])